plugin:
    name: 'mberizzo.products::lang.plugin.name'
    description: 'mberizzo.products::lang.plugin.description'
    author: mberizzo
    icon: oc-icon-list
    homepage: ''
permissions:
    products.module:
        tab: 'mberizzo.products::lang.plugin.name'
        label: 'mberizzo.products::lang.plugin.name'
navigation:
    main-menu-item:
        label: 'mberizzo.products::lang.plugin.name'
        url: mberizzo/products/products
        icon: icon-list
        permissions:
            - products.module
